events {}

http {

    map_hash_bucket_size 128;

    map $http_authorization $auth_ok {
        default 0;

        include /etc/nginx/tokens.map;
    }

    log_format llm '$remote_addr - $request';

    access_log /var/log/nginx/access.log llm;

    server {

        listen 8001 ssl;

        ssl_certificate     /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        client_max_body_size 100M;

        location / {

            if ($auth_ok = 0) {
                return 401;
            }

            proxy_pass http://vllm:8000;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_buffering off;
            proxy_request_buffering off;

            proxy_read_timeout 3600;
            proxy_send_timeout 3600;
        }
    }
}
